version: "3"

services:
  worker:
    image: quetzalarc/php:7.3-worker
    container_name: php-worker
    restart: unless-stopped
    volumes:
      - .:/usr/src/app
    logging:
      options:
        max-size: "1m"
        max-file: "1"

networks:
  default:
    external:
      name: worker
